version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0
    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
